CC=gcc -Wall

build:
	$(CC) main.c file_manager.h  file_manager.c time_full.h time_full.c -o main

test1:
	./main test 4 10 sys

test2:
	./main test 512 10 sys

test3:
	./main test 4096 10 sys

test4:
	./main test 8192 10 sys